---
Administrator:
  authentication:
    type: op
  class: Administrator
Scorekeeper:
  class: Scorekeeper
Insulter:
  class: Insulter
Twitter:
  class: Twitter
  respond_to_private_messages: true
Quote:
  class: Quote
  respond_to_private_messages: true
LadstFM:
  class: LastFM

